# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: s3-backup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/s3-backup
    ldflags:
      - -s -w
      - -X "github.com/fidrasofyan/s3-backup/internal/tasks.AppVersion={{.Version}}"
      - -X "github.com/fidrasofyan/s3-backup/internal/tasks.AppCommit={{.FullCommit}}"
      - -X "github.com/fidrasofyan/s3-backup/internal/tasks.AppBuildTime={{.Now}}"

changelog:
  use: github

archives:
  - id: binary
    formats: [binary]